sudo: false
language: node_js
node_js:
  - '6'
  - '7'
matrix:
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
script:
  - npm run build
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
